### PR TITLE
Remove Hypervisor mode from the PLIC spec

### PR DESCRIPTION
**Pull request by changab**
Remove Hypervisor mode from the PLIC spec because H-mode has been removed since RISC-V Privilege spec 1.10. Drop the obsoleted descriptions to avoid confusion.

### CODE REVIEW

**Comment by scottj97** [comment]
There is no more H privilege mode, but hypervisor still exists, with VS and VU modes, and CSRs including `hip` and `hie`, so is it really correct to remove all of this?

**Comment by scottj97** [comment]
Why does the commit author come from a different GitHub account than the PR creator?

**Comment by changab** [comment]
> Why does the commit author come from a different GitHub account than the PR creator?

I used the wrong account.

**Comment by lbmeng** [comment]
What happened to the following PRs?

https://github.com/riscv/riscv-plic-spec/pull/42
https://github.com/riscv/riscv-plic-spec/pull/43

**Pull request closed without merging**
